training:
  model_name: 'transformer'
  learning_rate: 0.8
  embedding_dim: 100
  num_heads: 1
  ff_dim: 128
  dropout_rate: 0.1
  epochs: 1
preprocessing:
  input_convertor: 'nn_vectorization'
  pretrained_embedding: './data/glove.twitter.27B.100d.txt'
  embedding_dim: 100
